# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/Hex_Editor/Hex_Editor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor || ORIG_REF_NAME==Hex_Editor} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_Debounce_Switch_0_0/Hex_Editor_Debounce_Switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_Debounce_Switch_0_0 || ORIG_REF_NAME==Hex_Editor_Debounce_Switch_0_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_Debounce_Switch_1_0/Hex_Editor_Debounce_Switch_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_Debounce_Switch_1_0 || ORIG_REF_NAME==Hex_Editor_Debounce_Switch_1_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_clk_wiz_0_0/Hex_Editor_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_clk_wiz_0_0 || ORIG_REF_NAME==Hex_Editor_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_num_capture_4bit_0_0/Hex_Editor_num_capture_4bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_num_capture_4bit_0_0 || ORIG_REF_NAME==Hex_Editor_num_capture_4bit_0_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_ScreenBufferMem_0_0/Hex_Editor_ScreenBufferMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_ScreenBufferMem_0_0 || ORIG_REF_NAME==Hex_Editor_ScreenBufferMem_0_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_VGA_timings_0_0/Hex_Editor_VGA_timings_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_VGA_timings_0_0 || ORIG_REF_NAME==Hex_Editor_VGA_timings_0_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_VGA_pattern_0_0/Hex_Editor_VGA_pattern_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_VGA_pattern_0_0 || ORIG_REF_NAME==Hex_Editor_VGA_pattern_0_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_AsciiCharsMem_0_0/Hex_Editor_AsciiCharsMem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_AsciiCharsMem_0_0 || ORIG_REF_NAME==Hex_Editor_AsciiCharsMem_0_0} -quiet] -quiet

# IP: bd/Hex_Editor/ip/Hex_Editor_Debounce_Switch_2_0/Hex_Editor_Debounce_Switch_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Hex_Editor_Debounce_Switch_2_0 || ORIG_REF_NAME==Hex_Editor_Debounce_Switch_2_0} -quiet] -quiet

# XDC: bd/Hex_Editor/Hex_Editor_ooc.xdc
